[package]
cairo-version = "=2.8.4"
name = "dojo_starter"
version = "1.0.10"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"                      # scarb run migrate
spawnPlayer = "sozo execute dojo_starter-actions spawnPlayer --wait"    # scarb run spawn
move = "sozo execute dojo_starter-actions move -c 1 --wait" # scarb run move
createDojo = "sozo execute dojo_starter-actions createDojomon -c 'B' 100 50 50 2 --wait"
catchDojo = "sozo execute dojo_starter-actions catchDojomon -c 1 --wait"



[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.10" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.10" }
